[pytest]
asyncio_mode = auto
testpaths = app/tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning:mediapipe.*
    ignore::UserWarning:tensorflow.*
log_cli = true
log_cli_level = WARNING
