"""
AuraFit — Style DNA System ORM models (Stage 8).

QuizSession:      One personality/lifestyle quiz attempt.
QuizResponse:     Individual question → answer within a session.
StyleDNAReport:   Full generated Style DNA report (extends StyleReport).
                  Aggregates all prior AI analysis (facial scan, color profile,
                  fragrance profile, wardrobe data, quiz responses) into one
                  coherent narrative document.
"""
from __future__ import annotations

import enum
import uuid

from sqlalchemy import Boolean, Enum, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import AuraFitBase, TimestampMixin, UUIDPrimaryKeyMixin


# ── Enums ─────────────────────────────────────────────────────────────────────

class QuizStatus(str, enum.Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED   = "completed"
    ABANDONED   = "abandoned"


class StyleDNAStatus(str, enum.Enum):
    QUEUED      = "queued"
    GENERATING  = "generating"
    READY       = "ready"
    FAILED      = "failed"


# ── Quiz models ───────────────────────────────────────────────────────────────

class QuizSession(AuraFitBase, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    One complete quiz session. A user can retake the quiz; each creates a
    new session. Only the most recent completed session is used for the
    Style DNA report.
    """
    __tablename__ = "quiz_sessions"

    user_id:        Mapped[uuid.UUID]  = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    quiz_version:   Mapped[str]        = mapped_column(String(10), nullable=False, default="2.0")
    status:         Mapped[QuizStatus] = mapped_column(Enum(QuizStatus, name="quiz_status_enum"), default=QuizStatus.IN_PROGRESS, nullable=False, index=True)
    current_step:   Mapped[int]        = mapped_column(Integer, default=0, nullable=False)
    total_steps:    Mapped[int]        = mapped_column(Integer, default=0, nullable=False)
    completed_at:   Mapped[str | None] = mapped_column(nullable=True)

    # Computed dimensions (populated when status → completed)
    # Personality axes [0, 1]
    style_axis:     Mapped[float | None] = mapped_column(Float, comment="0=classic, 1=avant-garde")
    energy_axis:    Mapped[float | None] = mapped_column(Float, comment="0=understated, 1=bold")
    structure_axis: Mapped[float | None] = mapped_column(Float, comment="0=relaxed, 1=tailored")
    occasion_mix:   Mapped[dict | None]  = mapped_column(JSONB, comment='{work:0.4, casual:0.4, evening:0.2}')
    lifestyle_tags: Mapped[list | None]  = mapped_column(JSONB, comment='["active","professional","creative"]')
    budget_tier:    Mapped[str | None]   = mapped_column(String(20))
    primary_archetype:  Mapped[str | None] = mapped_column(String(50))
    secondary_archetype:Mapped[str | None] = mapped_column(String(50))

    responses: Mapped[list["QuizResponse"]] = relationship(
        "QuizResponse", back_populates="session", cascade="all, delete-orphan",
        order_by="QuizResponse.question_index",
    )
    user: Mapped["User"] = relationship("User")


class QuizResponse(AuraFitBase, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    Single question-answer pair within a quiz session.
    answer_value is the raw selection (option_id or free text).
    answer_scores is a dict of dimension → score for this answer (pre-computed).
    """
    __tablename__ = "quiz_responses"

    session_id:      Mapped[uuid.UUID] = mapped_column(ForeignKey("quiz_sessions.id", ondelete="CASCADE"), nullable=False, index=True)
    question_id:     Mapped[str]       = mapped_column(String(50), nullable=False)
    question_index:  Mapped[int]       = mapped_column(Integer, nullable=False)
    answer_value:    Mapped[str | None]= mapped_column(Text, nullable=True)
    answer_options:  Mapped[list | None] = mapped_column(JSONB)  # Multi-select answers
    answer_scores:   Mapped[dict | None] = mapped_column(JSONB)  # Pre-computed dimension scores

    session: Mapped["QuizSession"] = relationship("QuizSession", back_populates="responses")


# ── Style DNA Report model ────────────────────────────────────────────────────

class StyleDNAReport(AuraFitBase, UUIDPrimaryKeyMixin, TimestampMixin):
    """
    The complete Style DNA Report — AuraFit's core flagship deliverable.

    Generated by assembling:
      - FacialScan analysis (skin tone, undertone, face shape, acne, symmetry)
      - ColorProfile (season, palette, makeup recs)
      - FragranceProfile (note families, preferences)
      - UserProfile (body shape, budget, style archetypes)
      - QuizSession (personality axes, lifestyle, occasions)
      - WardrobeItems (wardrobe utilisation, missing pieces)
      - InteractionHistory (top categories, brands)

    Each section is a structured JSON object rendered independently.
    The NLP engine generates personalised prose for each section.
    The PDF generator assembles sections into a branded PDF.
    """
    __tablename__ = "style_dna_reports"

    user_id:        Mapped[uuid.UUID]         = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    quiz_session_id:Mapped[uuid.UUID | None]  = mapped_column(ForeignKey("quiz_sessions.id", ondelete="SET NULL"), nullable=True)
    facial_scan_id: Mapped[uuid.UUID | None]  = mapped_column(ForeignKey("facial_scans.id", ondelete="SET NULL"), nullable=True)
    status:         Mapped[StyleDNAStatus]    = mapped_column(Enum(StyleDNAStatus, name="style_dna_status_enum"), default=StyleDNAStatus.QUEUED, nullable=False, index=True)
    report_version: Mapped[str]               = mapped_column(String(10), nullable=False, default="1.0")
    celery_task_id: Mapped[str | None]        = mapped_column(String(255), nullable=True)

    # ── Report sections (each rendered independently) ──────────────────────
    # headline:  short tagline personalised to the user
    # narrative: 2-3 sentence intro paragraph
    headline:  Mapped[str | None] = mapped_column(String(300))
    narrative: Mapped[str | None] = mapped_column(Text)

    # beauty_profile: overall beauty summary
    beauty_profile:   Mapped[dict | None] = mapped_column(JSONB)
    # skin_profile: tone, type, concerns, routine, ingredients
    skin_profile:     Mapped[dict | None] = mapped_column(JSONB)
    # color_profile: season, palette, makeup guide
    color_profile_section: Mapped[dict | None] = mapped_column(JSONB)
    # fashion_profile: archetypes, body shape tips, capsule wardrobe
    fashion_profile:  Mapped[dict | None] = mapped_column(JSONB)
    # fragrance_profile: note families, occasion matrix, top picks
    fragrance_profile_section: Mapped[dict | None] = mapped_column(JSONB)
    # hairstyle_profile: face shape, hair type, recommended styles, colours
    hairstyle_profile:Mapped[dict | None] = mapped_column(JSONB)
    # recommendations: curated product picks across all domains
    recommendations:  Mapped[dict | None] = mapped_column(JSONB)
    # personality: style axes, lifestyle summary, archetype description
    personality:      Mapped[dict | None] = mapped_column(JSONB)
    # occasion_guide: work | casual | evening | special occasion tips
    occasion_guide:   Mapped[dict | None] = mapped_column(JSONB)

    # ── Deliverable links ──────────────────────────────────────────────────
    pdf_s3_key:  Mapped[str | None] = mapped_column(String(512))
    pdf_url:     Mapped[str | None] = mapped_column(String(512))
    pdf_size_kb: Mapped[int | None] = mapped_column(Integer)

    # ── Data freshness ─────────────────────────────────────────────────────
    # Record the version hash of source data — detect when report is stale
    data_hash:   Mapped[str | None] = mapped_column(String(64), comment="SHA-256 of assembled input data")
    is_current:  Mapped[bool]       = mapped_column(Boolean, default=True, nullable=False, index=True)

    user: Mapped["User"] = relationship("User")
